# Test the email functionality with your Gmail account
# This script helps you set up Gmail SMTP for email sending

echo "🔧 Gmail SMTP Configuration Setup"
echo "=================================="
echo ""
echo "To enable email functionality with your Gmail account:"
echo ""
echo "1. Go to https://myaccount.google.com/security"
echo "2. Enable 2-Factor Authentication (if not already enabled)"
echo "3. Go to https://myaccount.google.com/apppasswords"
echo "4. Generate an App Password for 'Mail'"
echo "5. Copy the 16-character password"
echo ""
echo "6. Create a .env.local file in the project root with:"
echo ""
echo "DATABASE_URL=\"file:./prisma/dev.db\""
echo "NEXTAUTH_URL=\"http://localhost:3000\""
echo "NEXTAUTH_SECRET=\"$(openssl rand -base64 32)\""
echo ""
echo "# Email Configuration"
echo "SMTP_HOST=\"smtp.gmail.com\""
echo "SMTP_PORT=\"587\""
echo "SMTP_USER=\"your-actual-gmail@gmail.com\""
echo "SMTP_PASS=\"your-16-character-app-password\""
echo "EMAIL_FROM=\"The Missing Piece <your-actual-gmail@gmail.com>\""
echo ""
echo "7. Replace the placeholder values with your actual Gmail and app password"
echo ""
echo "🚀 Once configured, welcome emails will be sent automatically when:"
echo "   - Creating new tenants (business owners)"
echo "   - Creating new clients (wedding couples)"
echo ""
echo "✅ Emails include:"
echo "   - Branded welcome message"
echo "   - Secure password reset link (1-hour expiry)"
echo "   - Instructions for first-time login"
echo "   - Role-specific content (tenant vs client)"